language: haskell

dist: focal

ghc:
  - "9.4"
  - "9.6"
  - "9.8"

cabal: "3.10"

before_install:
  - sudo apt-get update
  - sudo apt-get install -y z3 libz3-dev

install:
  - cabal update
  - cabal build --only-dependencies --enable-tests

script:
  - cabal build
  - cabal test
  - cabal check
  - cabal sdist
